// 申万行业
const SHIndustry = {
  '610000': '建筑材料',
  '340000': '食品饮料',
  '330000': '家用电器',
  '110000': '农林牧渔',
  '280000': '汽车',
  '270000': '电子',
  '260000': '机械设备',
  '240000': '有色金属',
  '410000': '公用事业',
  '480000': '银行',
  '730000': '通信',
  '230000': '钢铁',
  '210000': '采掘',
  '450000': '商业贸易',
  '640000': '机械设备',
  '490000': '非银金融',
  '710000': '计算机',
  '350000': '纺织服装',
  '620000': '建筑装饰',
  '220000': '化工',
  '420000': '交通运输',
  '650000': '国防军工',
  '630000': '电气设备',
  '370000': '医药生物',
  '430000': '房地产',
  '360000': '轻工制造',
  '510000': '综合',
  '460000': '休闲服务',
  '720000': '传媒',
};

let SHIndustryList = [];
for (let k in SHIndustry) SHIndustryList.push({ name: SHIndustry[k], value: k });

let SHIndustryObj = {
    name: '申万行业',
    type: 'equalMultiOption',
    list: [
      {
        name: '',
        key: 'swIndustryTopLevelCode',
        hasSelectAll: false,
        list: SHIndustryList,
      },
    ],
  },
  directionObj = {
    name: '评级类型',
    type: 'equalSingle',
    list: [
      {
        hasSelectAll: false,
        key: ['changeDirection', 'zwChangeDirection'],
        list: [
          { name: '评级调高', value: '1', key: 'changeDirection' },
          { name: '评级调低', value: '2', key: 'changeDirection' },
          { name: '评级维持', value: '3', key: 'changeDirection' },
          { name: '评级展望正面', value: '1', key: 'zwChangeDirection' },
          { name: '评级展望负面', value: '3', key: 'zwChangeDirection' },
          { name: '评级展望稳定', value: '2', key: 'zwChangeDirection' },
          { name: '列入评级观察', value: '7', key: 'changeDirection' },
        ],
      },
    ],
  },
  areaObj = {
    name: '地区',
    type: 'equalMultiOption',
    list: [
      {
        hasSelectAll: false,
        key: 'area',
        list: [
          { name: '北京', value: '1100' },
          { name: '天津', value: '1200' },
          { name: '河北', value: '1300' },
          { name: '山西', value: '1400' },
          { name: '内蒙古', value: '1500' },
          { name: '辽宁', value: '2100' },
          { name: '吉林', value: '2200' },
          { name: '黑龙江', value: '2300' },
          { name: '上海', value: '3100' },
          { name: '江苏', value: '3200' },
          { name: '浙江', value: '3300' },
          { name: '安徽', value: '3400' },
          { name: '福建', value: '3500' },
          { name: '江西', value: '3600' },
          { name: '山东', value: '3700' },
          { name: '河南', value: '4100' },
          { name: '湖北', value: '4200' },
          { name: '湖南', value: '4300' },
          { name: '广东', value: '4400' },
          { name: '广西', value: '4500' },
          { name: '海南', value: '4600' },
          { name: '重庆', value: '5000' },
          { name: '四川', value: '5100' },
          { name: '贵州', value: '5200' },
          { name: '云南', value: '5300' },
          { name: '西藏', value: '5400' },
          { name: '陕西', value: '6100' },
          { name: '甘肃', value: '6200' },
          { name: '青海', value: '6300' },
          { name: '宁夏', value: '6400' },
          { name: '新疆', value: '6500' },
        ],
      },
    ],
  },
  incomeObj = {
    name: '筛选',
    type: 'equalMultiOption',
    list: [
      {
        hasSelectAll: false,
        name: '企业性质',
        key: 'enterpriseNature',
        list: [
          { name: '央企', value: '1' },
          { name: '地方国企', value: '2' },
          { name: '其他国企', value: '3' },
          { name: '民营企业', value: '4' },
          { name: '集体企业', value: '5' },
          { name: '外资企业', value: '6' },
          { name: '中外合资企业', value: '7' },
        ],
      },
      {
        hasSelectAll: false,
        key: 'isguarantee',
        name: '担保人',
        list: [{ name: '是', value: 1 }, { name: '否', value: 2 }],
      },
      {
        hasSelectAll: false,
        key: 'islgfp',
        name: '地方融资平台',
        list: [{ name: '是', value: 1 }, { name: '否', value: 2 }],
      },
      {
        name: '评级机构',
        key: 'raitingOrgCode',
        hasSelectAll: false,
        single: true,
        list: [
          { name: '中诚信国际', value: '80002154' },
          { name: '中诚信证券评估', value: '80000858' },
          { name: '鹏元资信', value: '80002099' },
          { name: '远东资信', value: '80002101' },
          { name: '联合信用', value: '80129270' },
          { name: '大公国际', value: '80002192' },
          { name: '新世纪评估', value: '80062388' },
          { name: '联合资信', value: '80002172' },
          { name: '东方金诚', value: '80117870' },
          { name: '中债资信', value: '80160465' },
          { name: '穆迪', value: '80065841' },
          { name: '标普', value: '80058815' },
          { name: '惠誉', value: '80065840' },
        ],
      },
    ],
  };

export default [directionObj, SHIndustryObj, areaObj, incomeObj];
